version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgres://user:password@host:port/database
      - REDIS_URL=redis://redis:6379
      - S3_BUCKET_NAME=your-s3-bucket
      - S3_ACCESS_KEY_ID=your-access-key-id
      - S3_SECRET_ACCESS_KEY=your-secret-access-key
      - OPEN_AI_KEY=OPEN_AI_KEY
      - AI_KEY=your-AI_KEY
    depends_on:
      - postgres
      - redis

  frontend:
    build: ./frontend
    ports:
      - '3001:3000'
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:3000

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    ports:
      - '5432:5432'

  redis:
    image: redis:6
    ports:
      - '6379:6379'
